# Generated by Django 3.2.16 on 2025-11-27 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание категории', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор категории в URL', unique=True, verbose_name='Слаг')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли категорию на сайте', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Москва, Луна, Дача', max_length=256, verbose_name='Название места')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли локацию на сайте', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок публикации', max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Текст публикации', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(help_text='Можно указать будущую дату для отложенной публикации', verbose_name='Дата и время публикации')),
                ('is_published', models.BooleanField(default=True, help_text='Если снять галочку — пост не будет отображаться на сайте', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Добавлено')),
                ('author', models.ForeignKey(help_text='Автор публикации', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится пост (обязательное поле)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категория')),
                ('location', models.ForeignKey(blank=True, help_text='Место, к которому относится пост; необязательно', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ('-pub_date',),
            },
        ),
    ]
